name = "navsphere"
compatibility_date = "2025-11-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liWuuFR7o18iPHUl"
GITHUB_OWNER = "NakamuraSama072"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere.nakamurasama072.com/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere.nakamurasama072.com/"

